### ISSUE TITLE
Proposal to make use of `redisConnectWithTimeout`

### ISSUE THREAD

**Issue by franckverrot** [matsumoto-r/mruby-redis#36]
We currently use `redisConnect` to connect to the Redis server. If hiredis cannot connect to the backend, it will timeout at some point but with some disadvantages compared to using `redisConnectWithTimeout` as there's no sensible default, and developers might want to tune that value (building [holycorn](https://github.com/franckverrot/holycorn)'s Redis data wrapper, I would like to give an opportunity to the users to override the defaults).

Asking the `mruby-redis` users, would you like that type of feature?

Thanks in advance!

**Comment by matsumoto-r** [comment]
I agree with you. If using timeout value, I like the following args:

```
r = Redis.new host, port, timeout
```

If timeout is undefined, `initialize` set default timeout value.
