### ISSUE TITLE
Proposal to make use of a custom exception in `mrb_redis_connect`

### ISSUE THREAD

**Issue by franckverrot** [matsumoto-r/mruby-redis#38]
We are currently raising a [`RuntimeError` exception in `mrb_redis_connect`](https://github.com/franckverrot/mruby-redis/blob/add-timeout/src/mrb_redis.c#L73). I would like to be able to fine-tune the `rescue` block of the callers by using a custom `Redis::ConnectionError` (or any other else that makes sense to the users) exception.

What do you think? I'll make a PR if you're OK with that.

**Comment by matsumoto-r** [comment]
It's nice! Could you make the PR?

**Comment by franckverrot** [comment]
Done! :-)
